/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class HotelReservation */

#ifndef _Included_HotelReservation
#define _Included_HotelReservation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     HotelReservation
 * Method:    consoleApp
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_HotelReservation_consoleApp
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
